### ISSUE TITLE
Cannot parse 'ghc,7.10.1,1' as PKG,VER,XREV,REL

### ISSUE THREAD

**Issue by LeifW** [listx/cabal2pkgbuild#5]
Running `initdb-sync` gives:
```
cblrepo add --distro-pkg ghc,7.10.1,1
option --distro-pkg: Cannot parse 'ghc,7.10.1,1' as PKG,VER,XREV,REL
```
The argument format cblrepo expects has been updated?
https://github.com/magthe/cblrepo/commit/fa351b2b4786250a828ea4274c0052935f8c4a2b

**Comment by listx** [comment]
Yes, I think you're right. `cabal2pkgbuild` is just a thin wrapper around `cblrepo`, so change in one must be taken into account in the other.

Unfortunately, I no longer have the resources to maintain this package, so feel free to fork it and modify on your own. The offending line is https://github.com/listx/cabal2pkgbuild/blob/master/cabal2pkgbuild.sh#L76 --- I am not sure what XREV means (I suggest trying `cblrepo add --help`).

On the other hand, I personally believe that `cabal2pkgbuild` has been obsoleted by the Nix package manager. Please see http://funloop.org/post/2015-02-10-using-nix-from-arch.html (I am the author of that blog).
